---
version: "3"

silent: true

tasks:
  default: ${GOTASK_BIN:-task} --list

  docker:build:
    desc: Build the docker image
    cmds:
      - docker compose build

  docker:run:
    desc: Run the docker image
    cmds:
      - docker compose run aur

  pkgb:gen:
    desc: Generate a PKGBUILD file
    summary: |
      Generates a PKGBUILD file from a template.
      Usage:

        task {{.TASK}} -- vendir
    cmds:
      - scripts/bin/gen_pkgbuild {{.CLI_ARGS}}

  pkgb:test:
    desc: Test a package by building it in a docker container
    summary: |
      Builds a package from the packages diretory in a docker container using makepkg.
      Usage:

        task {{.TASK}} -- vendir
    cmds:
      - docker compose run aur -c 'cd /tmp && /repo/scripts/bin/docker_make_pkg {{.CLI_ARGS}}'

  docs:update_readme:
    desc: Update the README.md file
    cmds:
      - scripts/bin/update_readme
